# Modify DLIB_PATH and EIGEN_PATH to adapt local environment

# Dlib dependency
DLIB_PATH := 
INC_PATH := -I$(DLIB_PATH)
LIB := $(DLIB_PATH)/examples/build/dlib_build/libdlib.a

# Eigen dependency
EIGEN_PATH := 
INC_PATH += -I$(EIGEN_PATH)

# rapidjson dependency
INC_PATH += -I../rapidjson/include

# Basic parameters
CXX = g++
CXX_FLAGS =
LINK_FLAGS = -lglog 

# OpenMP switch
USE_OpenMP := 0
ifeq ($(USE_OpenMP), 1)
    CXX_FLAGS += -DUSE_OMP -fopenmp
    LINK_FLAGS += -fopenmp
endif

# debug switch
DEBUG := 1
ifeq ($(DEBUG), 1)
    CXX_FLAGS += -g -O0
else
    CXX_FLAGS += -O2
endif

SRC = ADMM_Dlib.cpp ClassificationMultiClassDecFuxJoint.cpp data_function.cpp matlab_function.cpp OnlineUnsupTaskDrivDicLeaJointC.cpp ComputeCost.cpp SGDMultiClassQuadC.cpp multimodal_config_parser.cpp test_main.cpp
OBJ = $(SRC:.cpp=.o)

test: $(OBJ)
    $(CXX) -o $@ $^ $(LIB) $(LINK_FLAGS)

%.o: %.cpp
    $(CXX) -c $< $(INC_PATH) $(CXX_FLAGS)

tmp: test_tmp.cpp
    $(CXX) -o $@ $^ $(INC_PATH) $(CXX_FLAGS) $(LIB) $(LINK_FLAGS)

clean:
	rm -rf *.o test tmp
.PHONY: clean